package el.ka.rockdog.other

enum class Work {
  SIGN_UP,
  CHECK_FIELDS,
  SIGN_UP_PROCESS,
  LOG_IN,
  LOAD_PROFILE,
  CHANGE_PROFILE,
  SEND_REQUEST,
  SAVE_REQUEST,
  LOAD_REQUESTS_REG_ARTISTS,
  LOAD_REQUEST_DATA,
  DENY_REQUEST,
  APPROVE_REQUEST,
  LOAD_ARTISTS,
  LOAD_NOTIFICATIONS,
  DELETE_NOTIFICATION,
  DELETE_NOTIFICATION_FROM_PROFILE,
  CHANGE_ARTIST_COVER,
  ADD_PHOTO,
  DELETE_PHOTO,
  CHANGE_ARTIST_DESCRIPTION,
  DELETE_BAND_MEMBER,
  ADD_BAND_MEMBER
}